[package]
name = "snake"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16.1", features = ["wayland"] }
bevy-inspector-egui = { version = "0.33.1", optional = true }
rand = "0.9.2"

[features]
debug = ["dep:bevy-inspector-egui"]
